apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-media
  labels:
    app: recipes
spec:
  storageClassName: longhorn-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-static
  labels:
    app: recipes
spec:
  storageClassName: longhorn-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
